### ISSUE TITLE
Tiny roads zoning is not adjusted after Sunset Harbor

### ISSUE THREAD

**Issue by CMircea** [andreharv/NetworkExtensions#18]
This issue is with the version on the Steam Workshop; a build from the master branch works fine. Could you please release an update?

With workshop version:
![](https://i.imgur.com/rpeEwD2.png)

With build from master:
![](https://i.imgur.com/k5CBIwx.png)

**Comment by t1a2l** [comment]
@CMircea Can you send the build somehow ?

**Comment by ArronaxKP** [comment]
I can confirm what @CMircea says, Master build does fix tiny road zoning issue. 

Removed old link. See comment below

**Comment by AaronSadlerUK** [comment]
I also confirm this works. 

I have published this version on the workshop for those non techy people.

I compiled this with Visual Studio 2019, and all DLCs and content packs installed

https://steamcommunity.com/sharedfiles/filedetails/?id=2044086131

**Comment by CMircea** [comment]
@AaronSadlerUK it's not completely fixed though, see issue #19 I just opened.

**Comment by AaronSadlerUK** [comment]
For me at least this version works better than the current official workshop version, its only a temporary fix until the official version gets updated.

**Comment by AaronSadlerUK** [comment]
@CMircea You can close this now, the official mod has been updated
